services:
  project:
    build:
      context: docker/project/
    container_name: "project"
    volumes:
      - ./code:/code
    env_file:
      - .env
    command: >
      /bin/sh -c "python3 /code/manage.py makemigrations &&
                  python3 /code/manage.py migrate &&
                  python3 /code/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres


  db_postgres:
    image: postgres:14.6-alpine
    env_file:
      - .env
    volumes:
      - ./docker/postgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
