# Generated by Django 4.2.1 on 2023-05-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользоватеddль', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
